title: chundersnatch
markdown: kramdown
email: raystanza@js3tech.com
description: >- # ignore newlines until "baseurl:"
  Chundersnatch web page.
baseurl: "" # e.g. /docs
url: "https://raystanza.github.io/chundersnatch_jekyll"
twitter_username: chundersnatch
github_username:  raystanza

author:
  name: Jim Sines
  email: raystanza@js3tech.com
# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
